#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sm8750-common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/xiaomi/sm8750-common/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.bluetooth@aidl-service-qti-debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@aidl-service-qti-debug.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.drm-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.clearkey.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service-qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.health-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health-service.qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.power-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.sensors-service-multihal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors-service-multihal.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.thermal-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal-service.qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.usb-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb-service.qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.usb.gadget-service.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb.gadget-service.qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.wifi-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/hw/init.mi_thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mi_thermald.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.allocator-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.allocator-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.composer-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.composer-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.demura-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.demura-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf2-hal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf2-hal-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.wifi.wifilearner-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.wifi.wifilearner-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/perf/targetsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetsysnodesconfigs.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/permissions/android.hardware.hardware_keystore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.hardware_keystore.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/permissions/android.hardware.keystore.app_attest_key.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.keystore.app_attest_key.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/sm8750-common/proprietary/vendor/lib/hw/vulkan.adreno.so.tango:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.adreno.so.tango

PRODUCT_PACKAGES += \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    libCB \
    libOpenCL \
    libadreno_utils \
    libgsl \
    libllvm-glnext \
    libllvm-qcom \
    vendor.qti.hardware.display.snapalloc-impl \
    com.qualcomm.qti.dpm.api@1.0 \
    vendor.qti.hardware.bluetooth.finder-impl-qti \
    vendor.qti.hardware.bluetooth.xpanprovider-impl-qti \
    vendor.qti.hardware.bluetooth_sar@aidl-impl \
    libadsprpc \
    libcdsprpc \
    libfastcvopt \
    libidl \
    libmdsprpc \
    libqc2audio_hwaudiocodec \
    libqcci_legacy \
    libqdMetaData \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiextservices \
    libqmiservices \
    libqseed3 \
    libqservice \
    libqti-perfd-client \
    libqti-perfd \
    libqti-perfextn-intf \
    libqti-util \
    libqti-utils \
    libqtikeymaster4 \
    libqcompostprocbundle \
    libqcomvisualizer \
    libqcomvoiceprocessing \
    vendor.hardware.vibratorfeature.IVibratorExt-V1-ndk_platform \
    vendor.qti.hardware.bluetooth.xpanprovider-V1-ndk \
    vendor.qti.hardware.bluetooth_sar-V1-ndk \
    vendor.qti.hardware.display.composer3-V1-ndk \
    vendor.qti.hardware.display.config-V1-ndk \
    vendor.qti.hardware.display.config-V10-ndk \
    vendor.qti.hardware.display.config-V11-ndk \
    vendor.qti.hardware.display.config-V12-ndk \
    vendor.qti.hardware.display.config-V2-ndk \
    vendor.qti.hardware.display.config-V3-ndk \
    vendor.qti.hardware.display.config-V4-ndk \
    vendor.qti.hardware.display.config-V5-ndk \
    vendor.qti.hardware.display.config-V6-ndk \
    vendor.qti.hardware.display.config-V7-ndk \
    vendor.qti.hardware.display.config-V8-ndk \
    vendor.qti.hardware.display.config-V9-ndk \
    vendor.qti.hardware.display.demura-V1-ndk \
    vendor.qti.hardware.perf2-V1-ndk \
    vendor.qti.hardware.power.powermodule-V1-ndk \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.wifi.wifilearner-V1-ndk \
    vendor.qti.hardware.wigig.netperftuner@1.0 \
    vendor_lib_rfsa_adsp_activity_napp_header \
    vendor_lib_rfsa_adsp_activity_so \
    vendor_lib_rfsa_adsp_chre_qsh_shim_so \
    vendor_lib_rfsa_adsp_libDspIOProxy_skel_so \
    vendor_lib_rfsa_adsp_libhalide_hexagon_remote_skel_so \
    vendor_lib_rfsa_adsp_nearby_napp_header \
    vendor_lib_rfsa_adsp_nearby_so \
    com.qualcomm.qti.dpm.api@1.0 \
    vendor.qti.hardware.display.config-V1-ndk \
    vendor.qti.hardware.display.config-V10-ndk \
    vendor.qti.hardware.display.config-V11-ndk \
    vendor.qti.hardware.display.config-V12-ndk \
    vendor.qti.hardware.display.config-V2-ndk \
    vendor.qti.hardware.display.config-V3-ndk \
    vendor.qti.hardware.display.config-V4-ndk \
    vendor.qti.hardware.display.config-V5-ndk \
    vendor.qti.hardware.display.config-V6-ndk \
    vendor.qti.hardware.display.config-V7-ndk \
    vendor.qti.hardware.display.config-V8-ndk \
    vendor.qti.hardware.display.config-V9-ndk \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    QtiTelephonyService \
    dpmserviceapp \
    audiosphere \
    audiosphere.jar \
    com.qti.dpmframework \
    com.qti.dpmframework.jar \
    dpmapi \
    dpmapi.jar \
    qcrilhook \
    qcrilhook.jar \
    qti-telephony-common \
    qti-telephony-common.jar \
    android.hardware.health-service.qti.xml \
    android.hardware.security.keymint-service-qti.xml \
    android.hardware.thermal-service.qti.xml \
    bluetooth_audio.xml \
    bluetooth_hci.xml \
    bluetooth_sar.xml \
    vendor.qti.hardware.capabilityconfigstore-service.xml \
    vendor.qti.hardware.display.allocator-service.xml \
    vendor.qti.hardware.display.composer-service3_v3.xml \
    vendor.qti.hardware.display.demura-service.xml \
    vendor.qti.hardware.perf2.xml \
    vendor.qti.hardware.power.powermodule.xml \
    vendor.qti.hardware.wifi.wifilearner-service.xml \
    adsprpcd \
    cdsprpcd \
    cnss-daemon \
    cnss_diag \
    android.hardware.bluetooth@aidl-service-qti \
    android.hardware.drm-service.clearkey \
    android.hardware.gatekeeper-service-qti \
    android.hardware.health-service.qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.power-service \
    android.hardware.security.keymint-service-qti \
    android.hardware.sensors-service.multihal \
    android.hardware.thermal-service.qti \
    android.hardware.usb-service.qti \
    android.hardware.usb.gadget-service.qti \
    android.hardware.wifi-service \
    qcrilNrd \
    vendor.qti.hardware.capabilityconfigstore-service \
    vendor.qti.hardware.display.allocator-service \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.display.demura-service \
    vendor.qti.hardware.perf2-hal-service \
    irsc_util \
    mi_thermald \
    nv_mac \
    pd-mapper \
    sensors.qti \
    ssr_setup \
    thermal-engine-v2 \
    dpmd
